# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: deploy - calibration

env:
  node_version: 14
  git_email: jpschwartz2@uwalumni.com

on:
  push:
    branches: [primary]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [14]

    steps:
      - uses: actions/checkout@v2.3.4
        with:
          # fetch full history so things like auto-changelog work properly
          fetch-depth: 0
      - name: Use Node.js ${{ env.node_version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node_version }}

      - run: git config --global user.email "${{ env.git_email }}"
      - run: git config --global user.name "${{ github.actor }}"

      - name: Install
        run: npm ci --ignore-scripts

      - name: Test
        run: |
          npm run lint
          npm test

      - name: Tag
        run: npm version prerelease --preid calibration

      - name: Get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master

      - name: Build
        run: npm run export
        env:
          LOTUS_NODE_JSONRPC: 'https://calibration.node.glif.io'
          GRAPH_API_URL: 'graph.glif.host/query'
          COIN_TYPE: 't'
          HOME_URL: 'https://apps-calibration.glif.link'
          BLOG_URL: 'https://blog.glif.io'
          WALLET_URL: 'https://wallet-calibration.glif.link'
          SAFE_URL: 'https://safe-calibration.glif.link'
          EXPLORER_URL: 'https://explorer-calibration.glif.link'
          VERIFIER_URL: 'https://mainnet.verify.backend.glif.io'
          SENTRY_DSN: 'https://deb0795eeb874099961015e42a881020@o1126745.ingest.sentry.io/6229153'
          SENTRY_ENV: 'calibration'
          NODE_STATUS_API_KEY: 'm787669344-2a9b90eb03dbff3e503c93c7'
          NETWORK_IDENTIFIER: 'calibration'
          OAUTH_STATE_STRING: 'verifier'
          GITHUB_CLIENT_ID: '8e972b0441d34ebd94a3'
          GITHUB_REDIRECT_URL: 'https://github-oauth.glif.io/callback'

      - name: Deploy-cloudflare
        run: |
          npm i -g @cloudflare/wrangler
          npm run publish:calibration
        env:
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CF_ZONE_ID: ${{ secrets.CF_ZONE_ID }}
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}

      - name: Changelog
        uses: scottbrenner/generate-changelog-action@master
        id: Changelog

      - name: Filecoin-archive
        id: ipfs
        run: npm run store-ipfs
        env:
          WEB3_STORAGE_TOKEN: ${{ secrets.WEB3_STORAGE_TOKEN }}

      - name: Git-push
        run: |
          git push origin v${{ steps.package-version.outputs.current-version}}
          git push origin primary

      - name: Release-to-calibration
        uses: softprops/action-gh-release@v1
        with:
          name: Calibration release - v${{ steps.package-version.outputs.current-version }}
          tag_name: v${{ steps.package-version.outputs.current-version }}
          prerelease: true
          body: |
            Visit at: https://${{ steps.ipfs.outputs.cid }}.ipfs.dweb.link
            ${{ steps.Changelog.outputs.changelog }}
