name: gcp-build-push-deploy-mainnet

on:
  workflow_dispatch:

jobs:
  build:
    name: Mainnet Verifier Cloud Run Deployment
    env:
      MAINNET_GITHUB_CLIENT_ID: 8e972b0441d34ebd94a3
      MAINNET_GITHUB_REDIRECT_URL: https://github-oauth.glif.io/callback
      VERIFIER_URL: https://mainnet.verify.backend.glif.io
      OAUTH_STATE_STRING: verifier
      LOTUS_NODE_JSONRPC: https://api.node.glif.io
      NETWORK_IDENTIFIER: mainnet
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup GCP Service Account
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: 'latest'
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Configure Docker
        run: |
          gcloud auth configure-docker

      - name: Build
        run: |
          docker build \
          --build-arg GITHUB_CLIENT_ID=$MAINNET_GITHUB_CLIENT_ID \
          --build-arg GITHUB_REDIRECT_URL=$MAINNET_GITHUB_REDIRECT_URL \
          --build-arg VERIFIER_URL=$VERIFIER_URL \
          --build-arg OAUTH_STATE_STRING=$OAUTH_STATE_STRING \
          --build-arg LOTUS_NODE_JSONRPC=$LOTUS_NODE_JSONRPC \
          --build-arg NETWORK_IDENTIFIER=$NETWORK_IDENTIFIER \
          --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/mainnet-verifier-frontend:latest \
          .

      - name: Push
        run: |
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/mainnet-verifier-frontend:latest

      - name: Deploy
        run: |
          gcloud run deploy verifier-frontend-mainnet \
          --region=us-central1 \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/mainnet-verifier-frontend \
          --platform managed \
          --allow-unauthenticated \
          --project ${{ secrets.GCP_PROJECT_ID }}
