name: gcp-deploy

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build:
    name: Cloud Run Deployment
    env:
      NERPA_GITHUB_CLIENT_ID: 8861de8f921b556a4a0e
      NERPA_GITHUB_REDIRECT_URL: https://github-oauth.glif.io/callback
      VERIFIER_URL: https://verifier-nerpa-xhzgecibnq-uc.a.run.app
      OAUTH_STATE_STRING: nerpa-verifier
      LOTUS_NODE_JSONRPC: https://dev.node.glif.io/nerpa01/lotus/rpc/v0
      NETWORK_IDENTIFIER: nerpa
      IS_PROD: true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup GCP Service Account
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: 'latest'
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Deploy
        run: |
          gcloud run deploy verifier-frontend-nerpa \
          --region=us-central1 \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/verifier-frontend \
          --platform managed \
          --allow-unauthenticated \
          --set-env-vars=GITHUB_CLIENT_ID=${{ secrets.NERPA_GITHUB_CLIENT_ID }},GITHUB_REDIRECT_URL=${{ secrets.NERPA_GITHUB_REDIRECT_URL }},VERIFIER_URL=${{ secrets.VERIFIER_URL }},OAUTH_STATE_STRING=${{ secrets.OAUTH_STATE_STRING }},LOTUS_NODE_JSONRPC=${{ secrets.LOTUS_NODE_JSONRPC }},NETWORK_IDENTIFIER=${{ secrets.NETWORK_IDENTIFIER }},IS_PROD=${{ secrets.IS_PROD }} \
          --project ${{ secrets.GCP_PROJECT_ID }}
